// apps/web/tailwind.config.ts
import type { Config } from 'tailwindcss'
import path from 'path'

const config: Config = {
  content: [
    // path.join(__dirname) makes paths absolute so Tailwind finds
    // files no matter where the dev server is launched from
    path.join(__dirname, 'app/**/*.{js,ts,jsx,tsx,mdx}'),
    path.join(__dirname, 'components/**/*.{js,ts,jsx,tsx,mdx}'),
    path.join(__dirname, 'hooks/**/*.{js,ts,jsx,tsx,mdx}'),
    path.join(__dirname, 'services/**/*.{js,ts,jsx,tsx,mdx}'),
    path.join(__dirname, 'store/**/*.{js,ts,jsx,tsx,mdx}'),
    path.join(__dirname, 'types/**/*.{js,ts,jsx,tsx,mdx}'),
    path.join(__dirname, 'utils/**/*.{js,ts,jsx,tsx,mdx}'),
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── your existing brand colors ──────────────────────────
        'on-tertiary': '#ffffff',
        'surface-dim': '#cfdaf6',
        'secondary-fixed-dim': '#afc9ea',
        'secondary': '#47607e',
        'on-background': '#101b30',
        'primary-fixed': '#d7e2ff',
        'on-error': '#ffffff',
        'inverse-on-surface': '#edf0ff',
        'background': '#f9f9ff',
        'on-tertiary-fixed': '#002111',
        'inverse-primary': '#bbc6e2',
        'on-primary-container': '#79849d',
        'outline': '#74777d',
        'tertiary-fixed-dim': '#59de9b',
        'on-primary-fixed': '#101b30',
        'tertiary-container': '#002111',
        'on-surface': '#101b30',
        'surface-container-high': '#e0e8ff',
        'on-surface-variant': '#44474c',
        'surface-variant': '#d7e2ff',
        'surface': '#f9f9ff',
        'outline-variant': '#c4c6cc',
        'surface-container-highest': '#d7e2ff',
        'primary': '#0d1b2a',
        'surface-container': '#e8edff',
        'secondary-fixed': '#d1e4ff',
        'primary-container': '#0d1b2a',
        'surface-tint': '#545e76',
        'error-container': '#ffdad6',
        'inverse-surface': '#263046',
        'tertiary-fixed': '#59de9b',
        'error': '#ba1a1a',
        'on-secondary': '#ffffff',
        'surface-container-low': '#f1f3ff',
        'primary-fixed-dim': '#bbc6e2',
        'on-error-container': '#93000a',
        'secondary-container': '#c2dcff',
        'tertiary': '#000000',
        'on-tertiary-container': '#009760',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed': '#001d36',
        'on-secondary-container': '#48617e',
        'on-tertiary-fixed-variant': '#005232',
        'on-primary-fixed-variant': '#3c475d',
        'on-primary': '#ffffff',
        'on-secondary-fixed-variant': '#2f4865',
        // ── extra utility colors used in onboarding ─────────────
        'brand': '#005d8f',
        'brand-light': '#005d8f',
        'brand-muted': '#e8f2fb',
        'page-bg': '#f5f4f1',
        'card-bg': '#ffffff',
        'input-bg': '#f9fafb',
        'input-bg-focus': '#ffffff',
        'muted': '#6b7280',
        'subtle': '#9ca3af',
        'divider': '#f3f4f6',
        'success': '#16a34a',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.375rem',
        md: '0.625rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.25rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0,0,0,0.04), 0 4px 16px rgba(0,0,0,0.04)',
        'btn': '0 4px 14px rgba(0,93,143,0.25)',
        'btn-hover': '0 8px 24px rgba(0,93,143,0.4)',
        'avatar': '0 6px 20px rgba(0,0,0,0.18), 0 1px 4px rgba(0,0,0,0.08)',
        'avatar-hover': '0 8px 28px rgba(0,0,0,0.28), 0 2px 6px rgba(0,0,0,0.12)',
        'ring-brand': '0 0 0 3px rgba(0,93,143,0.08)',
      },
      animation: {
        'fade-up': 'fadeUp 0.4s ease both',
        'spin-fast': 'spin 0.7s linear infinite',
      },
      keyframes: {
        fadeUp: {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}

export default config